### ISSUE TITLE
Invalid Postgres downgrade SQL generated

### ISSUE THREAD

**Issue by robrwo** [frioux/DBIx-Class-DeploymentHandler#32]
An upgrade changed a column from integer to text.

The corresponding downgrade SQL was something like:
```sql
ALTER TABLE mytable ALTER COLUMN mycol TYPE integer;
```
In Postgres, tt should be:
```sql
ALTER TABLE mytable ALTER COLUMN mycol TYPE integer USING (my_col::integer);
```

Is this an SQL::Translator issue or a DBICDH issue?

**Comment by frioux** [comment]
Yeah that's a SQL::Translator issue, sorry!

**Comment by robrwo** [comment]
Reported in SQLT at https://rt.cpan.org/Ticket/Display.html?id=101704
