### ISSUE TITLE
Nothing differentiates schemata in version table

### ISSUE THREAD

**Issue by Altreus** [frioux/DBIx-Class-DeploymentHandler#34]
We build our applications out of Catalyst components, each of which may pull in a different model from a different DB package with its own DBIC schema in it.

As it stands, we can only use DeploymentHandler for one of them, because the version table doesn't have a way of specifying which Schema class the version number represents.

It would be great to be able to use DH for all of our schemata in the same database.

**Comment by frioux** [comment]
I'm not sure I understand; is your problem that the version table is underspecified so accidentally shared across DB's?

**Comment by Altreus** [comment]
Not quite; if you use a modular architecture, such that different Perl::Module::Schema classes can be written to the same physical database, only of them can be in the versions table.

So if I have

    My::WebApp::Main::Schema::Result::*
    My::Framework::Base::Schema::Result::*
    My::Framework::Plugin::Schema::Result::*

I can use inheritance or Roles to ensure that `My::WebApp::Main::Schema` implements `My::Framework::Base::Schema`, and thus extends it, and use `DeploymentHandler::VersionStorage::Standard::Component` there to deploy WebApp::Main + Framework::Base.

But I can't have the Framework::Plugin schema independent of these. I'd have to compose them at the DBIC level, while so far we've been able to keep plugins almost completely separate from everything else. That's because the `dbix_class_deploymenthandler_versions` table can only hold one schema's versioning; either My::WebApp::Main::Schema or My::Framework::Plugin::Schema.

For Postgres, this is not so much of a problem, because Postgres has database > schema > table, but in my previous life with MySQL there's no schema in the middle to separate them. Also true of SQLite, which is probably going to be used reasonably often (by us, for example) to test things.

**Comment by frioux** [comment]
I think the solution to this is to create a different version table per schema.  I documented how to set a diff version table [here](https://metacpan.org/pod/distribution/DBIx-Class-DeploymentHandler/lib/DBIx/Class/DeploymentHandler/Cookbook/CustomResultSource.pod).  Does this not solve the problem completely generically?

**Comment by Altreus** [comment]
That's very useful, and it does. Thanks!
