### ISSUE TITLE
[PATCH] fix a spelling mistake

### ISSUE THREAD

**Issue by gregoa** [frioux/DBIx-Class-DeploymentHandler#37]
In Debian we are currently applying the following patch to
DBIx-Class-DeploymentHandler.
We thought you might be interested in it too.

    Description: fix a spelling mistake
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2015-10-17
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdbix-class-deploymenthandler-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by frioux** [comment]
Applied and released; Thanks as usual!

**Comment by gregoa** [comment]
On Sat, 31 Oct 2015 16:35:43 -0700, fREW Schmidt wrote:

> Applied and released; Thanks as usual!

Thanks!
Uploaded to Debian/unstable.


Cheers,
gregor

-- 
 .''`.  Homepage: http://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: U2: Mission Impossible Theme
