### ISSUE TITLE
It's hard to find out to ->new

### ISSUE THREAD

**Issue by frioux** [frioux/DBIx-Class-DeploymentHandler#42]

**Comment by mohawk2** [comment]
@frioux Could you spell this out slightly?

**Comment by frioux** [comment]
Yeah I think the issue I opened four years ago (haha) was that if you look at https://metacpan.org/pod/DBIx::Class::DeploymentHandler it's hard to figure out where the doc for ->new is; IIRC it's basically all in the parent class, ::Dad
