### ISSUE TITLE
database_version rename backwards compatibility issue

### ISSUE THREAD

**Issue by TBSliver** [frioux/DBIx-Class-DeploymentHandler#64]
The change from database_version to initial_version may cause issues in existing deployments - we had a client where we needed an override for the version result table, which meant that we needed to provide our own core class to pull in the override.

It may be worth adding either a handles on `initial_version`, or a deprecation notice on `database_version` in HandlesVersioning, or at least mentioning it in the Changes file that the `database_version` attribute on VersionHandlers has been renamed.

The commit that brought in this change was fc5489884a78beb54e21498e8c53600f70d50b93 for reference

**Comment by mohawk2** [comment]
Thanks for the report! Feel like PR-ing on Changes? If you also want to PR the `handles` stuff as well, please include tests :-)
