### ISSUE TITLE
Changes in 0.002225 to use Package::Variant breaks some custom code

### ISSUE THREAD

**Issue by robrwo** [frioux/DBIx-Class-DeploymentHandler#67]
We have some custom code that extends this and uses DBIx::Class::DeploymentHandler::WithApplicatorDumple directly.  This change has broken things, since Moose does not consider this a role.

Why not use [MooX::Role::Parameterized](https://metacpan.org/pod/MooX::Role::Parameterized)?

**Comment by mohawk2** [comment]
Done. See 0.002229.
