### ISSUE TITLE
$DBIx::Class::DeploymentHandler::VERSION

### ISSUE THREAD

**Issue by augensalat** [frioux/DBIx-Class-DeploymentHandler#73]
Module should have a `$VERSION`:
```
$ perl -MDBIx::Class::DeploymentHandler\ 99
DBIx::Class::DeploymentHandler does not define $DBIx::Class::DeploymentHandler::VERSION--version check failed.
BEGIN failed--compilation aborted.
```

**Comment by frioux** [comment]
It does: https://metacpan.org/release/DBIx-Class-DeploymentHandler/source/lib/DBIx/Class/DeploymentHandler.pm#L2

**Comment by augensalat** [comment]
Ah, I see. So this is done in build?
The problem with this module is that building is a real PITA - or should I say ditaa?
While developing it does not have a module `$VERSION`.

**Comment by frioux** [comment]
Yeah dzil does it at release time.

--
